"use client";

import { Activity, ArrowLeft, CalendarPlus, Clipboard, FileDown, FileText, HeartPulse, Pill, Printer, Search, Stethoscope, TestTube, Weight } from "lucide-react";
import Link from "next/link";
import { useMemo, useState } from "react";
import { usePathname, useRouter, useSearchParams } from "next/navigation";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import type { ClinicalMeasurement, LongitudinalDashboardData, MeasurementType } from "@/lib/longitudinal/types";

type Period = "30d" | "3m" | "6m" | "1y" | "2y" | "all";
const periods: Array<{ value: Period; label: string; days: number | null }> = [{ value: "30d", label: "30 dias", days: 30 }, { value: "3m", label: "3 meses", days: 90 }, { value: "6m", label: "6 meses", days: 180 }, { value: "1y", label: "1 ano", days: 365 }, { value: "2y", label: "2 anos", days: 730 }, { value: "all", label: "Todo o período", days: null }];
const measurementMeta: Record<MeasurementType, { label: string; icon: typeof Activity }> = {
  weight: { label: "Peso", icon: Weight }, bmi: { label: "IMC", icon: Activity }, blood_pressure: { label: "Pressão arterial", icon: HeartPulse }, heart_rate: { label: "Frequência cardíaca", icon: Activity }, glucose: { label: "Glicemia", icon: TestTube }, temperature: { label: "Temperatura", icon: Activity }, oxygen_saturation: { label: "Saturação", icon: Activity },
};

function date(value: string) { return new Intl.DateTimeFormat("pt-BR").format(new Date(value.includes("T") ? value : `${value}T12:00:00`)); }
function age(birthDate: string | null) { if (!birthDate) return null; const birth = new Date(`${birthDate}T12:00:00`); const now = new Date(); let value = now.getFullYear() - birth.getFullYear(); if (now < new Date(now.getFullYear(), birth.getMonth(), birth.getDate())) value--; return value; }
function displayValue(item: ClinicalMeasurement) { return item.type === "blood_pressure" ? `${item.value}/${item.secondaryValue}` : new Intl.NumberFormat("pt-BR", { maximumFractionDigits: 1 }).format(item.value); }

function TrendChart({ type, values }: { type: MeasurementType; values: ClinicalMeasurement[] }) {
  const points = [...values].sort((a, b) => a.measuredAt.localeCompare(b.measuredAt));
  if (points.length < 2) return null;
  const allValues = points.flatMap((point) => point.secondaryValue === null ? [point.value] : [point.value, point.secondaryValue]);
  const min = Math.min(...allValues); const max = Math.max(...allValues); const span = max - min || 1;
  const xy = (point: ClinicalMeasurement, index: number, secondary = false) => ({ x: 24 + (index / Math.max(points.length - 1, 1)) * 552, y: 170 - (((secondary ? point.secondaryValue : point.value) ?? point.value) - min) / span * 130 });
  const path = (secondary = false) => points.map((point, index) => { const p = xy(point, index, secondary); return `${index ? "L" : "M"}${p.x},${p.y}`; }).join(" ");
  return <Card className="shadow-none"><CardHeader className="pb-2"><CardTitle className="text-base">{measurementMeta[type].label}</CardTitle><p className="text-xs text-muted-foreground">{points.length} registros · {points[0].unit}</p></CardHeader><CardContent><div className="overflow-x-auto"><svg viewBox="0 0 600 210" role="img" aria-label={`Evolução de ${measurementMeta[type].label}: ${points.map((item) => `${date(item.measuredAt)}, ${displayValue(item)} ${item.unit}`).join("; ")}`} className="min-w-[520px]"><line x1="24" y1="170" x2="576" y2="170" stroke="currentColor" opacity=".2"/><path d={path()} fill="none" stroke="var(--primary)" strokeWidth="3"/>{type === "blood_pressure" && <path d={path(true)} fill="none" stroke="var(--warning)" strokeWidth="3" strokeDasharray="7 5"/>}{points.map((point, index) => { const p = xy(point, index); return <g key={point.id}><circle cx={p.x} cy={p.y} r="5" fill="var(--primary)"><title>{date(point.measuredAt)} · {displayValue(point)} {point.unit} · {point.professionalName || "Profissional não informado"}</title></circle><text x={p.x} y="195" textAnchor="middle" fontSize="10" fill="currentColor" opacity=".7">{date(point.measuredAt).slice(0, 5)}</text></g>; })}</svg></div>{type === "blood_pressure" && <p className="text-xs text-muted-foreground"><span className="text-primary">Linha contínua: sistólica</span> · <span className="text-amber-700">tracejada: diastólica</span></p>}<details className="mt-3 text-sm"><summary className="cursor-pointer font-medium">Tabela acessível e origem</summary><div className="mt-2 overflow-x-auto"><table className="w-full text-left text-xs"><thead><tr><th className="p-2">Data</th><th className="p-2">Valor</th><th className="p-2">Origem</th><th className="p-2">Ação</th></tr></thead><tbody>{points.map((point) => <tr key={point.id} className="border-t"><td className="p-2">{date(point.measuredAt)}</td><td className="p-2">{displayValue(point)} {point.unit}</td><td className="p-2">Prontuário · {point.professionalName || "Não informado"}</td><td className="p-2">{point.appointmentId && <Link className="text-primary underline" href={`/consultas/${point.appointmentId}/prontuario`}>Visualizar atendimento</Link>}</td></tr>)}</tbody></table></div></details></CardContent></Card>;
}

export function LongitudinalDashboard({ data }: { data: LongitudinalDashboardData }) {
  const router = useRouter(); const pathname = usePathname(); const searchParams = useSearchParams();
  const initial = periods.some((item) => item.value === searchParams.get("period")) ? searchParams.get("period") as Period : "1y";
  const [period, setPeriod] = useState<Period>(initial); const [query, setQuery] = useState(""); const [copied, setCopied] = useState(false);
  const cutoff = useMemo(() => { const days = periods.find((item) => item.value === period)?.days; if (!days) return null; const value = new Date(); value.setDate(value.getDate() - days); return value; }, [period]);
  const inPeriod = (value: string) => !cutoff || new Date(value) >= cutoff;
  const measurements = data.measurements.filter((item) => inPeriod(item.measuredAt));
  const visits = data.visits.filter((item) => inPeriod(item.date));
  const documents = data.documents.filter((item) => inPeriod(item.date));
  const timeline = data.timeline.filter((item) => inPeriod(item.date));
  const latest = [...new Map(measurements.map((item) => [item.type, item])).values()];
  const diagnoses = useMemo(() => { const map = new Map<string, { label: string; count: number; first: string; last: string; appointments: string[] }>(); visits.forEach((visit) => { const label = (visit.cid10 || visit.assessment)?.trim(); if (!label) return; const key = label.toLocaleLowerCase("pt-BR"); const current = map.get(key); if (current) { current.count++; current.first = visit.date < current.first ? visit.date : current.first; current.last = visit.date > current.last ? visit.date : current.last; current.appointments.push(visit.appointmentId); } else map.set(key, { label, count: 1, first: visit.date, last: visit.date, appointments: [visit.appointmentId] }); }); return [...map.values()].filter((item) => item.label.toLocaleLowerCase("pt-BR").includes(query.toLocaleLowerCase("pt-BR"))).sort((a, b) => b.last.localeCompare(a.last)); }, [query, visits]);
  const prescriptions = documents.filter((item) => ["prescription", "special_prescription"].includes(item.type));
  const exams = documents.filter((item) => item.type === "exam_request");
  const patientAge = age(data.patient.birth_date);
  const setSelectedPeriod = (value: Period) => { setPeriod(value); const params = new URLSearchParams(searchParams); params.set("period", value); router.replace(`${pathname}?${params.toString()}`, { scroll: false }); };
  const summaryText = [`Resumo clínico longitudinal para revisão profissional.`, `Paciente: ${data.patient.social_name || data.patient.full_name}`, `Período: ${periods.find((item) => item.value === period)?.label}`, `Consultas: ${visits.length}`, `Alergias: ${data.patient.allergies || "Não informado"}`, `Condições crônicas: ${data.patient.comorbidities || "Não informado"}`, `Medicamentos contínuos informados: ${data.patient.continuous_medications || "Não informado"}`, ...latest.map((item) => `${measurementMeta[item.type].label}: ${displayValue(item)} ${item.unit} em ${date(item.measuredAt)}`), `Gerado em: ${new Date().toLocaleString("pt-BR")}`].join("\n");
  return <section className="space-y-4 print:space-y-3">
    <header className="flex flex-col gap-3 rounded-xl border bg-card p-4 lg:flex-row lg:items-center lg:justify-between"><div className="min-w-0"><Button variant="ghost" size="sm" className="-ml-2 print:hidden" render={<Link href={`/patients/${data.patient.id}`} />}><ArrowLeft /> Perfil</Button><h1 className="truncate text-2xl font-semibold">{data.patient.social_name || data.patient.full_name}</h1><p className="text-sm text-muted-foreground">{[patientAge === null ? null : `${patientAge} anos`, data.patient.gender, data.patient.insurance, data.lastVisit ? `Última consulta ${date(data.lastVisit.date)}` : "Sem consultas", `${data.visits.length} atendimento(s)`, data.responsibleProfessional].filter(Boolean).join(" · ")}</p></div><div className="flex flex-wrap gap-2 print:hidden">{data.latestAppointmentId && <Button size="sm" variant="outline" render={<Link href={`/consultas/${data.latestAppointmentId}/prontuario`} />}><Stethoscope /> Voltar ao prontuário</Button>}<Button size="sm" variant="outline" render={<Link href={`/appointments/new?patient=${data.patient.id}`} />}><CalendarPlus /> Nova consulta</Button><Button size="sm" variant="outline" onClick={() => window.print()}><Printer /> Imprimir/PDF</Button><Button size="sm" variant="outline" onClick={async () => { await navigator.clipboard.writeText(summaryText); setCopied(true); window.setTimeout(() => setCopied(false), 2000); }}><Clipboard /> {copied ? "Copiado" : "Copiar resumo"}</Button></div></header>
    <Card className="shadow-none"><CardContent className="grid gap-3 p-4 sm:grid-cols-2 xl:grid-cols-4"><div><p className="text-xs font-medium text-muted-foreground">Alergias</p><p className="text-sm">{data.patient.allergies || "Não informado"}</p></div><div><p className="text-xs font-medium text-muted-foreground">Condições crônicas</p><p className="text-sm">{data.patient.comorbidities || "Não informado"}</p></div><div><p className="text-xs font-medium text-muted-foreground">Medicamentos contínuos informados</p><p className="text-sm">{data.patient.continuous_medications || "Não informado"}</p></div><div><p className="text-xs font-medium text-muted-foreground">Fontes indisponíveis no modelo atual</p><p className="text-sm text-muted-foreground">{data.unavailableSources.join("; ")}</p></div></CardContent></Card>
    <nav className="flex gap-1 overflow-x-auto rounded-lg border bg-card p-2 print:hidden" aria-label="Filtrar período">{periods.map((item) => <Button key={item.value} size="sm" variant={period === item.value ? "secondary" : "ghost"} aria-pressed={period === item.value} className="shrink-0" onClick={() => setSelectedPeriod(item.value)}>{item.label}</Button>)}</nav>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{latest.map((item) => { const Icon = measurementMeta[item.type].icon; const series = measurements.filter((entry) => entry.type === item.type); const previous = series[1]; return <Card key={item.type} className="shadow-none"><CardContent className="p-4"><div className="flex items-center justify-between"><p className="text-sm font-medium">{measurementMeta[item.type].label}</p><Icon className="size-4 text-primary" /></div><p className="mt-2 text-2xl font-semibold">{displayValue(item)} <span className="text-sm font-normal text-muted-foreground">{item.unit}</span></p><p className="text-xs text-muted-foreground">{date(item.measuredAt)}{previous ? ` · variação ${item.value - previous.value > 0 ? "+" : ""}${(item.value - previous.value).toFixed(1)}` : " · sem registro anterior"}</p></CardContent></Card>; })}<Card className="shadow-none"><CardContent className="p-4"><p className="text-sm font-medium">Atividade no período</p><p className="mt-2 text-sm">{visits.length} consultas · {prescriptions.length} prescrições · {exams.length} solicitações de exames</p></CardContent></Card></div>
    {!measurements.length && <p className="rounded-lg border border-dashed p-6 text-center text-sm text-muted-foreground">Nenhuma medição estruturável foi encontrada no período. Ausência de registro não significa normalidade.</p>}
    <div className="grid gap-4 xl:grid-cols-2">{(Object.keys(measurementMeta) as MeasurementType[]).map((type) => <TrendChart key={type} type={type} values={measurements.filter((item) => item.type === type)} />)}</div>
    <div className="grid gap-4 xl:grid-cols-2"><Card className="shadow-none"><CardHeader><CardTitle className="flex items-center gap-2 text-lg"><HeartPulse className="size-5 text-primary"/> Diagnósticos e CIDs</CardTitle><label className="relative mt-2"><Search className="absolute top-2.5 left-3 size-4 text-muted-foreground"/><input value={query} onChange={(event) => setQuery(event.target.value)} className="h-9 w-full rounded-md border bg-background pl-9 text-sm" placeholder="Pesquisar diagnóstico ou CID"/></label></CardHeader><CardContent>{diagnoses.length ? <div className="space-y-2">{diagnoses.map((item) => <div key={item.label} className="rounded-lg border p-3"><div className="flex justify-between gap-2"><strong className="text-sm">{item.label}</strong><Badge variant="outline">{item.count} ocorrência(s)</Badge></div><p className="mt-1 text-xs text-muted-foreground">Primeira: {date(item.first)} · última: {date(item.last)}</p><Link href={`/consultas/${item.appointments[0]}/prontuario`} className="mt-2 inline-block text-xs text-primary underline">Abrir atendimento mais recente</Link></div>)}</div> : <p className="text-sm text-muted-foreground">Nenhum diagnóstico ou CID registrado no período.</p>}</CardContent></Card><Card className="shadow-none"><CardHeader><CardTitle className="flex items-center gap-2 text-lg"><Pill className="size-5 text-primary"/> Medicamentos</CardTitle></CardHeader><CardContent className="space-y-3"><div><p className="text-xs font-semibold">Informados como uso contínuo</p><p className="text-sm">{data.patient.continuous_medications || "Não informado"}</p></div><div><p className="text-xs font-semibold">Prescrições no período</p>{prescriptions.length ? prescriptions.map((doc) => <div key={doc.id} className="mt-2 rounded-lg border p-3"><Link className="text-sm font-medium text-primary underline" href={`/documentos/${doc.id}`}>{doc.title}</Link><p className="text-xs text-muted-foreground">{date(doc.date)} · situação: {doc.status === "issued" ? "prescrito" : doc.status}</p>{doc.items.length > 0 && <p className="mt-1 text-sm">{doc.items.map((item) => item.medication_name).join("; ")}</p>}</div>) : <p className="text-sm text-muted-foreground">Nenhuma prescrição documental encontrada.</p>}</div><p className="text-xs text-muted-foreground">Uma prescrição anterior não confirma uso atual. Suspensão e encerramento não possuem fonte estruturada no modelo atual.</p></CardContent></Card></div>
    <div className="grid gap-4 xl:grid-cols-2"><Card className="shadow-none"><CardHeader><CardTitle className="flex items-center gap-2 text-lg"><TestTube className="size-5 text-primary"/> Exames</CardTitle></CardHeader><CardContent>{exams.length ? <div className="space-y-2">{exams.map((doc) => <div key={doc.id} className="rounded-lg border p-3"><Link href={`/documentos/${doc.id}`} className="text-sm font-medium text-primary underline">{doc.title}</Link><p className="text-xs text-muted-foreground">Solicitado em {date(doc.date)} · {doc.status}</p></div>)}</div> : <p className="text-sm text-muted-foreground">Nenhuma solicitação de exame encontrada no período. Resultados laboratoriais estruturados ainda não existem nesta fonte.</p>}</CardContent></Card><Card className="shadow-none"><CardHeader><CardTitle className="flex items-center gap-2 text-lg"><FileText className="size-5 text-primary"/> Eventos e documentos</CardTitle></CardHeader><CardContent>{documents.length ? <div className="space-y-2">{documents.slice(0, 12).map((doc) => <Link key={doc.id} href={`/documentos/${doc.id}`} className="block rounded-lg border p-3 hover:bg-muted/50"><strong className="text-sm">{doc.title}</strong><p className="text-xs text-muted-foreground">{date(doc.date)} · {doc.status}</p></Link>)}</div> : <p className="text-sm text-muted-foreground">Nenhum documento clínico no período.</p>}</CardContent></Card></div>
    <Card className="shadow-none"><CardHeader><CardTitle className="flex items-center gap-2 text-lg"><FileDown className="size-5 text-primary"/> Timeline resumida</CardTitle></CardHeader><CardContent>{timeline.length ? <ol className="space-y-2">{timeline.slice(0, 30).map((event) => <li key={event.id}><details className="rounded-lg border"><summary className="cursor-pointer p-3 text-sm font-medium">{date(event.date)}{event.time ? ` · ${event.time}` : ""} — {event.title}</summary><div className="space-y-2 border-t p-3 text-sm">{event.details.map((detail) => <p key={detail.label}><strong>{detail.label}:</strong> {detail.value}</p>)}{event.href && <Link className="text-primary underline" href={event.href}>Visualizar atendimento</Link>}</div></details></li>)}</ol> : <p className="text-sm text-muted-foreground">Nenhum evento encontrado no período selecionado.</p>}</CardContent></Card>
    <footer className="text-xs text-muted-foreground">Resumo clínico longitudinal para revisão profissional. Gerado em {new Date().toLocaleString("pt-BR")}. Nenhum dado foi interpretado clinicamente ou enviado automaticamente a serviço externo.</footer>
  </section>;
}
