"use client";
import { Building2, ChevronDown } from "lucide-react";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { toast } from "sonner";
import { createClient } from "@/lib/supabase/client";
import { Button } from "@/components/ui/button";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuLabel, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import type { Clinic } from "@/lib/clinics/types";
export function ClinicSwitcher() { const router = useRouter(); const [clinics, setClinics] = useState<Clinic[]>([]); const [active, setActive] = useState<Clinic | null>(null); useEffect(() => { const supabase = createClient(); void (async () => { const { data: { user } } = await supabase.auth.getUser(); if (!user) return; const { data: profile } = await supabase.from("profiles").select("active_clinic_id").eq("id", user.id).maybeSingle(); const { data: members } = await supabase.from("clinic_members").select("clinic:clinics(*)").eq("user_id", user.id).eq("status", "active"); const available = (members ?? []).map((item) => item.clinic).filter(Boolean) as unknown as Clinic[]; setClinics(available); setActive(available.find((clinic) => clinic.id === profile?.active_clinic_id) ?? available[0] ?? null); })(); }, []); async function change(clinic: Clinic) { const { error } = await createClient().rpc("set_active_clinic", { target_clinic_id: clinic.id }); if (error) return toast.error("Não foi possível trocar de clínica."); setActive(clinic); toast.success(`Clínica ativa: ${clinic.name}`); router.refresh(); } return <DropdownMenu><DropdownMenuTrigger asChild><Button variant="outline" size="sm" className="max-w-52 cursor-pointer justify-between"><span className="flex min-w-0 items-center gap-2"><Building2 className="size-4" /><span className="truncate">{active?.name ?? "Clínica"}</span></span><ChevronDown className="size-4" /></Button></DropdownMenuTrigger><DropdownMenuContent align="start" className="w-56"><DropdownMenuLabel>Clínica ativa</DropdownMenuLabel>{clinics.map((clinic) => <DropdownMenuItem key={clinic.id} onSelect={() => change(clinic)}>{clinic.name}{clinic.id === active?.id && " · ativa"}</DropdownMenuItem>)}</DropdownMenuContent></DropdownMenu>; }
