"use client";

import { Activity, AlertTriangle, Beaker, CalendarClock, ChevronDown, ClipboardList, FileText, HeartPulse, Pill, Search, ShieldAlert, Stethoscope } from "lucide-react";
import Link from "next/link";
import { useDeferredValue, useEffect, useMemo, useState } from "react";

import { Badge } from "@/components/ui/badge";
import type { MedicalRecordAppointment, MedicalRecordHistoryItem } from "@/lib/medical-records/types";
import { buildPatientTimelineEvents, type PatientTimelineDocument } from "@/lib/medical-records/patient-timeline";

function date(value: string | null | undefined) { return value ? new Intl.DateTimeFormat("pt-BR").format(new Date(value.includes("T") ? value : `${value}T12:00:00`)) : "Não registrado"; }
function age(value: string | null) { if (!value) return "Não informada"; const birth = new Date(`${value}T12:00:00`); const now = new Date(); let years = now.getFullYear() - birth.getFullYear(); if (now < new Date(now.getFullYear(), birth.getMonth(), birth.getDate())) years--; return `${years} anos`; }
function lines(value: string | null | undefined) { return value?.split(/\n|;/).map((item) => item.trim()).filter(Boolean) ?? []; }
function findVital(text: string | null, names: string[]) { if (!text) return null; for (const name of names) { const match = text.match(new RegExp(`${name}\\s*[:=]\\s*([^;|\\n]+)`, "i")); if (match?.[1]) return match[1].trim(); } return null; }

const documentLabels: Record<string, string> = { prescription: "Receita", special_prescription: "Receita especial", medical_certificate: "Atestado", attendance_declaration: "Declaração", exam_request: "Solicitação de exames", referral: "Encaminhamento", patient_guidance: "Orientações" };

export function PatientContextWorkspace({ appointment, history, documents }: { appointment: MedicalRecordAppointment; history: MedicalRecordHistoryItem[]; documents: PatientTimelineDocument[] }) {
  const storageKey = `aster:clinical-workspace:${appointment.id}:expanded`;
  const [expanded, setExpanded] = useState(true); const [query, setQuery] = useState(""); const deferredQuery = useDeferredValue(query.trim().toLocaleLowerCase("pt-BR"));
  useEffect(() => { const timer = window.setTimeout(() => { const stored = window.sessionStorage.getItem(storageKey); if (stored !== null) setExpanded(stored === "true"); }, 0); return () => window.clearTimeout(timer); }, [storageKey]);
  useEffect(() => { window.sessionStorage.setItem(storageKey, String(expanded)); }, [expanded, storageKey]);
  useEffect(() => { if (!appointment.patient) return; window.sessionStorage.setItem(`aster:patient-context:${appointment.patient_id}`, JSON.stringify({ cachedAt: new Date().toISOString(), patient: { id: appointment.patient.id, birthDate: appointment.patient.birth_date, createdAt: appointment.patient.created_at, gender: appointment.patient.gender, insurance: appointment.patient.insurance } })); }, [appointment.patient, appointment.patient_id]);

  const events = useMemo(() => buildPatientTimelineEvents(history, documents), [documents, history]);
  const filteredEvents = useMemo(() => !deferredQuery ? events : events.filter((event) => event.searchableText.includes(deferredQuery)), [deferredQuery, events]);
  const diagnoses = useMemo(() => history.flatMap((item) => lines(item.assessment).map((description, index) => ({ id: `${item.id}:${index}`, cid: lines(item.cid10)[index] || item.cid10, description, date: item.appointment_date }))).slice(0, 8), [history]);
  const medications = useMemo(() => lines(appointment.patient?.continuous_medications), [appointment.patient?.continuous_medications]);
  const allergies = useMemo(() => lines(appointment.patient?.allergies), [appointment.patient?.allergies]);
  const clinicalText = [appointment.patient?.medical_history, appointment.patient?.allergies, appointment.patient?.continuous_medications, ...history.slice(0, 5).flatMap((item) => [item.assessment, item.medications])].filter(Boolean).join(" ").toLocaleLowerCase("pt-BR");
  const alerts = [{ term: /anticoagul/, label: "Uso de anticoagulante" }, { term: /gesta(nte|ção|cao)/, label: "Gestante" }, { term: /diabet/, label: "Diabetes registrada" }, { term: /hipertens/, label: "Hipertensão registrada" }, { term: /risco cardiovascular|cardiopat/, label: "Risco cardiovascular" }, { term: /insufici.ncia renal|doença renal|doenca renal/, label: "Condição renal registrada" }].filter((item) => item.term.test(clinicalText)).map((item) => item.label);
  if (allergies.some((item) => /grave|anafil|choque/i.test(item))) alerts.push("Alergia potencialmente grave");
  const indicators = [{ label: "Peso", names: ["Peso"] }, { label: "IMC", names: ["IMC"] }, { label: "Pressão arterial", names: ["PA", "Pressão arterial"] }, { label: "Glicemia", names: ["Glicemia"] }, { label: "Frequência cardíaca", names: ["FC", "Frequência cardíaca"] }, { label: "Temperatura", names: ["Temperatura"] }].map((indicator) => ({ ...indicator, values: history.map((item) => findVital(item.vital_signs, indicator.names)).filter((value): value is string => Boolean(value)).slice(0, 5).reverse() })).filter((item) => item.values.length);
  const pending = [...history.filter((item) => item.exam_requests && !documents.some((doc) => doc.appointment_id === item.appointment_id && doc.document_type === "exam_result")).slice(0, 3).map((item) => ({ label: "Exame solicitado sem resultado estruturado", detail: item.exam_requests!, date: item.appointment_date })), ...history.filter((item) => item.return_guidance && new Date(item.appointment_date) < new Date()).slice(0, 2).map((item) => ({ label: "Retorno a revisar", detail: item.return_guidance!, date: item.appointment_date }))];

  return <section className="overflow-hidden rounded-lg border border-primary/20 bg-card shadow-sm" aria-labelledby="clinical-workspace-title"><button type="button" className="flex min-h-11 w-full items-center gap-2 px-3 text-left" onClick={() => setExpanded((current) => !current)} aria-expanded={expanded}><Stethoscope className="size-4 text-primary" /><span id="clinical-workspace-title" className="text-sm font-semibold">Workspace Clínico</span><span className="ml-auto text-xs text-muted-foreground">Memória clínica somente leitura</span><ChevronDown className={`size-4 transition-transform ${expanded ? "rotate-180" : ""}`} /></button>
    {expanded && <div className="space-y-3 border-t p-3"><label className="relative block"><Search className="absolute top-1/2 left-3 size-4 -translate-y-1/2 text-muted-foreground" /><input type="search" value={query} onChange={(event) => setQuery(event.target.value)} className="h-9 w-full rounded-md border bg-background pr-3 pl-9 text-sm outline-none focus-visible:ring-3 focus-visible:ring-ring/50" placeholder="Pesquisar consulta, receita, CID, documento ou exame" /></label>
      <div className="grid gap-3 xl:grid-cols-3"><Panel icon={Activity} title="Resumo clínico"><dl className="grid grid-cols-2 gap-2 text-xs"><Fact label="Idade" value={age(appointment.patient?.birth_date ?? null)} /><Fact label="Sexo" value={appointment.patient?.gender} /><Fact label="Convênio" value={appointment.patient?.insurance || "Particular"} /><Fact label="Médico" value={appointment.professional?.full_name} /><Fact label="Última consulta" value={date(history[0]?.appointment_date)} /><Fact label="Paciente desde" value={date(appointment.patient?.created_at)} /></dl></Panel>
        <Panel icon={HeartPulse} title="Problemas ativos">{diagnoses.length ? diagnoses.map((item) => <Row key={item.id} title={item.description} meta={`${item.cid || "CID não estruturado"} · ${date(item.date)}`} badge="Registrado" />) : <Empty text="Nenhum problema ativo registrado" />}</Panel>
        <Panel icon={ShieldAlert} title="Alergias">{allergies.length ? allergies.map((item) => <Row key={item} title={item} meta="Tipo, gravidade e observações não estruturados" />) : <Empty text="Nenhuma alergia registrada" />}</Panel>
        <Panel icon={Pill} title="Medicamentos em uso">{medications.length ? medications.map((item) => <Row key={item} title={item} meta="Dose, frequência, início e prescritor não estruturados" />) : <Empty text="Nenhum medicamento contínuo registrado" />}</Panel>
        <Panel icon={AlertTriangle} title="Alertas clínicos" tone="warning">{alerts.length ? alerts.map((item) => <Row key={item} title={item} />) : <Empty text="Nenhum alerta derivado dos registros disponíveis" />}</Panel>
        <Panel icon={Beaker} title="Últimos exames">{documents.filter((item) => item.document_type === "exam_request").slice(0, 5).map((item) => <Row key={item.id} title={item.title} meta={`${date(item.issued_at || item.created_at)} · Resultado não estruturado`} href={`/documentos/${item.id}`} />)}{!documents.some((item) => item.document_type === "exam_request") && <Empty text="Nenhum exame disponível" />}</Panel>
        <Panel icon={FileText} title="Documentos recentes">{documents.slice(0, 5).map((item) => <Row key={item.id} title={item.title} meta={`${documentLabels[item.document_type] || "Documento"} · ${date(item.issued_at || item.created_at)}`} href={`/documentos/${item.id}`} />)}{!documents.length && <Empty text="Nenhum documento recente" />}</Panel>
        <Panel icon={CalendarClock} title="Timeline resumida">{filteredEvents.slice(0, 6).map((event) => <Row key={event.id} title={event.title} meta={`${date(event.date)} · ${event.status || "Registrado"}`} href={event.href || undefined} />)}{!filteredEvents.length && <Empty text="Nenhum evento encontrado" />}</Panel>
        <Panel icon={Activity} title="Indicadores">{indicators.length ? indicators.map((item) => <div key={item.label} className="py-1"><p className="text-xs font-medium">{item.label}</p><div className="mt-1 flex h-7 items-end gap-1">{item.values.map((value, index) => <span key={`${value}:${index}`} className="min-w-7 flex-1 rounded-t bg-primary/20 px-1 pt-1 text-center text-[9px] text-primary" style={{ height: `${Math.min(100, 40 + index * 12)}%` }} title={value}>{value}</span>)}</div></div>) : <Empty text="Sem histórico suficiente para gráficos" />}</Panel>
        <Panel icon={ClipboardList} title="Pendências">{pending.length ? pending.map((item, index) => <Row key={`${item.label}:${index}`} title={item.label} meta={`${item.detail} · ${date(item.date)}`} />) : <Empty text="Nenhuma pendência identificada nas fontes disponíveis" />}</Panel></div>
    </div>}
  </section>;
}

function Panel({ icon: Icon, title, tone, children }: { icon: typeof Activity; title: string; tone?: "warning"; children: React.ReactNode }) { return <section className={`max-h-64 overflow-y-auto rounded-lg border p-3 ${tone === "warning" ? "border-amber-500/30 bg-amber-500/5" : "bg-muted/10"}`}><h3 className="mb-2 flex items-center gap-2 text-xs font-semibold"><Icon className="size-4 text-primary" />{title}</h3><div className="divide-y">{children}</div></section>; }
function Fact({ label, value }: { label: string; value: string | null | undefined }) { return <div><dt className="text-muted-foreground">{label}</dt><dd className="mt-0.5 font-medium">{value || "Não informado"}</dd></div>; }
function Row({ title, meta, badge, href }: { title: string; meta?: string; badge?: string; href?: string }) { const content = <div className="py-2"><div className="flex items-start gap-2"><p className="min-w-0 flex-1 text-xs font-medium">{title}</p>{badge && <Badge variant="outline" className="text-[9px]">{badge}</Badge>}</div>{meta && <p className="mt-1 text-[10px] text-muted-foreground">{meta}</p>}</div>; return href ? <Link href={href} className="block hover:text-primary">{content}</Link> : content; }
function Empty({ text }: { text: string }) { return <p className="py-3 text-xs text-muted-foreground">{text}</p>; }
