import { ArrowLeft, CalendarDays, Pencil, ShieldCheck } from "lucide-react";
import Link from "next/link";
import { notFound } from "next/navigation";
import { getPatient } from "@/app/(dashboard)/patients/actions";
import { PatientActions } from "@/components/patients/patient-actions";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { formatCpf, formatDate } from "@/lib/patients/format";

function Detail({ label, value }: { label: string; value: string | null }) { return <div><p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">{label}</p><p className="mt-1 text-sm">{value || "Não informado"}</p></div>; }
export default async function PatientPage({ params }: { params: Promise<{ id: string }> }) { const { id } = await params; const patient = await getPatient(id); if (!patient) notFound(); const initials = patient.full_name.split(" ").slice(0, 2).map((part) => part[0]).join(""); return <section><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><Button variant="ghost" size="sm" render={<Link href="/patients" />} className="mb-2 -ml-2"><ArrowLeft /> Pacientes</Button><div className="flex items-center gap-3"><Avatar size="lg"><AvatarImage src={patient.photo_url ?? undefined} alt="" /><AvatarFallback className="bg-primary/10 font-semibold text-primary">{initials}</AvatarFallback></Avatar><div><h1 className="text-2xl font-semibold tracking-[-0.03em] sm:text-3xl">{patient.full_name}</h1><p className="mt-1 text-sm text-muted-foreground">CPF {formatCpf(patient.cpf)}</p></div></div></div><div className="flex gap-2"><Button variant="outline" render={<Link href={`/patients/${id}/edit`} />}><Pencil /> Editar</Button><PatientActions id={id} name={patient.full_name} /></div></div><div className="mt-7 grid gap-6 xl:grid-cols-[1.2fr_0.8fr]"><Card className="shadow-none"><CardHeader><CardTitle>Dados pessoais</CardTitle></CardHeader><CardContent className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3"><Detail label="Nascimento" value={formatDate(patient.birth_date)} /><Detail label="Sexo" value={patient.gender} /><Detail label="Estado civil" value={patient.marital_status} /><Detail label="Profissão" value={patient.occupation} /><Detail label="CNS" value={patient.cns} /><Detail label="E-mail" value={patient.email} /></CardContent></Card><Card className="shadow-none"><CardHeader><CardTitle>Contato</CardTitle></CardHeader><CardContent className="space-y-5"><Detail label="Telefone" value={patient.phone} /><Detail label="WhatsApp" value={patient.whatsapp} /><Detail label="Emergência" value={patient.emergency_contact} /><Detail label="Endereço" value={[patient.address, patient.city, patient.state, patient.zip_code].filter(Boolean).join(", ")} /></CardContent></Card><Card className="shadow-none"><CardHeader><CardTitle className="flex items-center gap-2"><ShieldCheck className="size-4 text-primary" /> Convênio</CardTitle></CardHeader><CardContent className="grid gap-5 sm:grid-cols-2"><Detail label="Convênio" value={patient.insurance} /><Detail label="Carteirinha" value={patient.insurance_card} /></CardContent></Card><Card className="shadow-none"><CardHeader><CardTitle className="flex items-center gap-2"><CalendarDays className="size-4 text-primary" /> Informações clínicas</CardTitle></CardHeader><CardContent className="space-y-5"><Detail label="Alergias" value={patient.allergies} /><Detail label="Comorbidades" value={patient.comorbidities} /><Detail label="Observações" value={patient.notes} /></CardContent></Card></div></section>; }
