import type { ExamCatalogItem } from "@/lib/clinical-plan/types";

// Catálogo demonstrativo e isolado. Não substitui terminologia oficial,
// protocolos assistenciais ou validação profissional.
export const mockExamCatalog: ExamCatalogItem[] = [
  {
    id: "hemogram",
    name: "Hemograma completo",
    category: "Exames laboratoriais",
    type: "exam",
    abbreviation: "HC",
    synonyms: ["hemograma"],
  },
  {
    id: "fasting-glucose",
    name: "Glicemia de jejum",
    category: "Exames laboratoriais",
    type: "exam",
    synonyms: ["glicose"],
  },
  {
    id: "electrocardiogram",
    name: "Eletrocardiograma",
    category: "Exames cardiológicos",
    type: "exam",
    abbreviation: "ECG",
    synonyms: ["ecg"],
  },
  {
    id: "chest-xray",
    name: "Radiografia de tórax",
    category: "Exames de imagem",
    type: "exam",
    synonyms: ["raio x de tórax"],
  },
  {
    id: "abdominal-ultrasound",
    name: "Ultrassonografia de abdome",
    category: "Exames de imagem",
    type: "exam",
    abbreviation: "USG abdome",
    synonyms: ["ultrassom abdominal", "ultrassonografia abdominal"],
  },
  {
    id: "hba1c",
    name: "Hemoglobina glicada",
    category: "Exames laboratoriais",
    type: "exam",
    abbreviation: "HbA1c",
    synonyms: ["hemoglobina glicosilada"],
  },
  {
    id: "creatinine",
    name: "Creatinina",
    category: "Exames laboratoriais",
    type: "exam",
    synonyms: ["função renal"],
  },
  {
    id: "urea",
    name: "Ureia",
    category: "Exames laboratoriais",
    type: "exam",
    synonyms: ["função renal"],
  },
  {
    id: "lipid-profile",
    name: "Perfil lipídico",
    category: "Exames laboratoriais",
    type: "exam",
    synonyms: ["colesterol", "triglicerídeos"],
  },
  {
    id: "alt",
    name: "Alanina aminotransferase",
    category: "Exames laboratoriais",
    type: "exam",
    abbreviation: "ALT/TGP",
    synonyms: ["função hepática", "tgp"],
  },
  {
    id: "ast",
    name: "Aspartato aminotransferase",
    category: "Exames laboratoriais",
    type: "exam",
    abbreviation: "AST/TGO",
    synonyms: ["função hepática", "tgo"],
  },
  {
    id: "tsh",
    name: "Hormônio tireoestimulante",
    category: "Exames laboratoriais",
    type: "exam",
    abbreviation: "TSH",
    synonyms: ["tireoide"],
  },
  {
    id: "upper-endoscopy",
    name: "Endoscopia digestiva alta",
    category: "Exames endoscópicos",
    type: "diagnostic_procedure",
    abbreviation: "EDA",
    synonyms: ["endoscopia"],
  },
];
