import { AlertCircle, CalendarCheck, CalendarDays, ClipboardList, Clock3, FileWarning, HeartHandshake, Plus, RotateCcw, UserPlus, UsersRound } from "lucide-react";
import Link from "next/link";

import { getDashboardData } from "@/app/(dashboard)/dashboard/actions";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card,CardContent,CardHeader,CardTitle } from "@/components/ui/card";
import { appointmentStatusLabels,appointmentTypeLabels,type AppointmentStatus } from "@/lib/appointments/types";

const statusOrder:AppointmentStatus[]=["confirmed","waiting","in_progress","completed","cancelled","no_show"];
const roleLabel:Record<string,string>={doctor:"Médico",receptionist:"Recepção",clinic_admin:"Administrador",admin:"Administrador",demo:"Leitura"};

export default async function DashboardPage(){
 const data=await getDashboardData(); const reception=data.user.role==="receptionist"; const readOnly=data.user.role==="demo"; const date=new Intl.DateTimeFormat("pt-BR",{dateStyle:"full",timeZone:"America/Bahia"}).format(new Date());
 const pending=reception?[{label:"Retornos para agendar",value:data.pending.awaitingReturn,href:"/continuidade",icon:RotateCcw},{label:"Pendências sem responsável",value:data.pending.unassigned,href:"/continuidade",icon:HeartHandshake},{label:"Consultas sem confirmação",value:data.pending.unconfirmed,href:"/appointments",icon:Clock3}]:[{label:"Prontuários não finalizados",value:data.pending.unfinishedRecords,href:"/appointments",icon:ClipboardList},{label:"Resultados para revisar",value:data.pending.results,href:"/continuidade",icon:FileWarning},{label:"Retornos pendentes",value:data.pending.awaitingReturn,href:"/continuidade",icon:RotateCcw},{label:"Pendências vencidas",value:data.pending.overdueContinuity,href:"/continuidade",icon:HeartHandshake},{label:"Documentos em rascunho",value:data.pending.documents,href:"/appointments",icon:FileWarning}];
 const indicators=[{label:"Novos pacientes no mês",value:String(data.indicators.newPatients),icon:UserPlus},{label:"Consultas no mês",value:String(data.indicators.monthlyAppointments),icon:CalendarDays},{label:"Taxa de comparecimento",value:`${data.indicators.attendanceRate}%`,icon:CalendarCheck},{label:"Retornos agendados",value:String(data.indicators.scheduledReturns),icon:RotateCcw}];
 return <main className="min-w-0 space-y-5 overflow-x-hidden pb-[max(2rem,env(safe-area-inset-bottom))]">
  <header className="flex flex-col gap-4 rounded-xl border bg-background p-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-sm text-muted-foreground">{roleLabel[data.user.role]??data.user.role} · {data.user.clinicName}</p><h1 className="mt-1 text-2xl font-semibold tracking-tight">Olá, {data.user.name.split(" ")[0]}</h1><p className="mt-1 text-sm text-muted-foreground">{date} · {data.today.total} atendimento(s) previsto(s) hoje.</p></div>{!readOnly&&<div className="flex flex-wrap gap-2">{reception?<><Button render={<Link href="/appointments/new"/>}><Plus/>Novo agendamento</Button><Button variant="outline" render={<Link href="/recepcao"/>}>Abrir Recepção</Button></>:<><Button render={<Link href="/appointments?view=day"/>}><CalendarDays/>Abrir Agenda</Button><Button variant="outline" render={<Link href="/continuidade"/>}>Abrir pendências</Button></>}</div>}</header>
  {data.error&&<p role="alert" className="flex items-center gap-2 rounded-xl border border-destructive/30 bg-destructive/5 p-3 text-sm text-destructive"><AlertCircle className="size-4"/>{data.error}</p>}
  <section aria-labelledby="day-summary"><h2 id="day-summary" className="mb-2 text-sm font-semibold">Resumo do dia</h2><div className="grid grid-cols-2 gap-2 sm:grid-cols-4 xl:grid-cols-8"><Metric label="Agendados" value={data.today.total}/>{statusOrder.map((status)=><Metric key={status} label={appointmentStatusLabels[status]} value={data.today[status]}/>)}<Metric label="Atrasados" value={data.today.late} alert={Boolean(data.today.late)}/></div></section>
  <div className="grid min-w-0 gap-5 xl:grid-cols-[1.4fr_1fr]">
   <Card className="shadow-none"><CardHeader className="flex flex-row items-center justify-between"><CardTitle>Fluxo operacional</CardTitle><Button size="sm" variant="ghost" render={<Link href={reception?"/recepcao":"/appointments"}/>}>Abrir origem</Button></CardHeader><CardContent className="space-y-2">{data.sectionErrors.agenda?<SectionError text={data.sectionErrors.agenda}/>:data.upcoming.map((item)=><div key={item.id} className="flex min-w-0 flex-col gap-2 rounded-lg border p-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex min-w-0 gap-3"><strong className="tabular-nums">{item.start_time.slice(0,5)}</strong><div className="min-w-0"><p className="truncate text-sm font-medium">{item.patient?.full_name??"Paciente"}</p><p className="truncate text-xs text-muted-foreground">{item.professional?.full_name} · {appointmentTypeLabels[item.appointment_type]}</p></div></div><div className="flex items-center gap-2"><Badge variant="secondary">{appointmentStatusLabels[item.status]}</Badge><Button size="sm" render={<Link href={item.status==="in_progress"?`/consultas/${item.id}/prontuario`:`/appointments/${item.id}`}/>}>{item.status==="in_progress"?"Continuar":"Abrir"}</Button></div></div>)}{!data.upcoming.length&&!data.sectionErrors.agenda&&<Empty text="Não há pacientes aguardando ou em atendimento."/>}</CardContent></Card>
   <Card className="shadow-none"><CardHeader><CardTitle>Pendências e alertas</CardTitle></CardHeader><CardContent className="space-y-2">{pending.map(({label,value,href,icon:Icon})=><Link key={label} href={href} className="flex items-center justify-between rounded-lg border p-3 hover:bg-muted/40"><span className="flex items-center gap-2 text-sm"><Icon className="size-4 text-muted-foreground"/>{label}</span><Badge variant={value?"destructive":"secondary"}>{value}</Badge></Link>)}</CardContent></Card>
  </div>
  <div className="grid min-w-0 gap-5 xl:grid-cols-2">
   <Card className="shadow-none"><CardHeader className="flex flex-row items-center justify-between"><CardTitle>Continuidade do cuidado</CardTitle><Button size="sm" variant="ghost" render={<Link href="/continuidade"/>}>Ver todas</Button></CardHeader><CardContent className="space-y-2">{data.sectionErrors.continuity?<SectionError text={data.sectionErrors.continuity}/>:data.continuity.map((item)=><Link key={item.id} href="/continuidade" className="block rounded-lg border p-3 hover:bg-muted/40"><div className="flex justify-between gap-2"><p className="text-sm font-medium">{item.title}</p><Badge variant={item.due_at&&new Date(item.due_at)<new Date()?"destructive":"outline"}>{item.status}</Badge></div><p className="mt-1 text-xs text-muted-foreground">{item.patient?.full_name??"Paciente"} · {item.item_type}</p></Link>)}{!data.continuity.length&&!data.sectionErrors.continuity&&<Empty text="Não há retornos ou pendências clínicas em aberto."/>}</CardContent></Card>
   <Card className="shadow-none"><CardHeader><CardTitle>Documentos recentes</CardTitle></CardHeader><CardContent className="space-y-2">{data.sectionErrors.documents?<SectionError text={data.sectionErrors.documents}/>:data.documents.map((doc)=><Link key={doc.id} href={`/documentos/${doc.id}`} className="flex items-center justify-between gap-2 rounded-lg border p-3 hover:bg-muted/40"><div className="min-w-0"><p className="truncate text-sm font-medium">{doc.title}</p><p className="truncate text-xs text-muted-foreground">{doc.patient?.full_name??"Paciente"} · {doc.document_type}</p></div><Badge variant={doc.status==="draft"?"secondary":"outline"}>{doc.status}</Badge></Link>)}{!data.documents.length&&!data.sectionErrors.documents&&<Empty text="Não existem documentos recentes."/>}</CardContent></Card>
  </div>
  <section aria-labelledby="period-indicators"><h2 id="period-indicators" className="mb-2 text-sm font-semibold">Indicadores do mês</h2>{data.sectionErrors.indicators?<SectionError text={data.sectionErrors.indicators}/>:<div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{indicators.map(({label,value,icon:Icon})=><Card key={label} className="gap-2 py-4 shadow-none"><CardHeader className="flex flex-row items-center justify-between px-4"><CardTitle className="text-xs text-muted-foreground">{label}</CardTitle><Icon className="size-4 text-primary"/></CardHeader><CardContent className="px-4"><p className="text-2xl font-semibold">{value}</p></CardContent></Card>)}</div>}</section>
 </main>;
}
function Metric({label,value,alert=false}:{label:string;value:number;alert?:boolean}){return <div className={`rounded-lg border p-3 ${alert?"border-destructive/30 bg-destructive/5":""}`}><p className="truncate text-xs text-muted-foreground">{label}</p><p className="mt-1 text-xl font-semibold">{value}</p></div>}
function Empty({text}:{text:string}){return <div className="py-8 text-center"><UsersRound className="mx-auto size-6 text-muted-foreground"/><p className="mt-2 text-sm text-muted-foreground">{text}</p></div>}
function SectionError({text}:{text:string}){return <p role="alert" className="rounded-lg border border-amber-500/30 bg-amber-500/5 p-3 text-sm text-amber-800">{text} Atualize a página para tentar novamente.</p>}
