"use server";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { createClient } from "@/lib/supabase/server";
import type { Clinic, ClinicMember, ClinicRole } from "@/lib/clinics/types";
import { createClient as createAdminClient } from "@supabase/supabase-js";
import { getSiteUrl } from "@/lib/site-url";

const inviteSchema = z.object({ email: z.string().email(), full_name: z.string().min(3).max(160), role: z.enum(["clinic_admin", "doctor", "secretary", "receptionist"]) });
async function context() { const supabase = await createClient(); if (!supabase) return { error: "Supabase não configurado." as const }; const { data: auth } = await supabase.auth.getUser(); if (!auth.user) return { error: "Não autenticado." as const }; const { data: profile } = await supabase.from("profiles").select("active_clinic_id").eq("id", auth.user.id).maybeSingle(); const { data: member } = profile?.active_clinic_id ? await supabase.from("clinic_members").select("role, status").eq("clinic_id", profile.active_clinic_id).eq("user_id", auth.user.id).maybeSingle() : { data: null }; if (!profile?.active_clinic_id || !member || member.status !== "active" || !["clinic_admin", "platform_admin"].includes(member.role)) return { error: "Sem permissão para administrar esta clínica." as const }; return { supabase, user: auth.user, clinicId: profile.active_clinic_id, role: member.role as ClinicRole }; }
export async function getClinicContext() { const current = await context(); if ("error" in current) return { clinic: null as Clinic | null, members: [] as ClinicMember[], error: current.error ?? "Sem permissão." }; const [{ data: clinic }, { data: members }] = await Promise.all([current.supabase.from("clinics").select("*").eq("id", current.clinicId).single(), current.supabase.from("clinic_members").select("*, profile:profiles(full_name, email, phone)").eq("clinic_id", current.clinicId).order("created_at")]); return { clinic: clinic as Clinic | null, members: (members ?? []) as ClinicMember[], error: null }; }
export async function inviteClinicMember(input: unknown) { const parsed = inviteSchema.safeParse(input); if (!parsed.success) return { error: "Dados do convite inválidos." }; const current = await context(); if ("error" in current) return { error: current.error }; const url = process.env.NEXT_PUBLIC_SUPABASE_URL; const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY; if (!url || !serviceKey) return { error: "Configure SUPABASE_SERVICE_ROLE_KEY apenas no servidor para enviar convites." }; const admin = createAdminClient(url, serviceKey, { auth: { autoRefreshToken: false, persistSession: false } }); const { data, error } = await admin.auth.admin.inviteUserByEmail(parsed.data.email, { data: { full_name: parsed.data.full_name }, redirectTo: `${getSiteUrl()}/auth/callback` }); if (error || !data.user) return { error: error?.message ?? "Não foi possível enviar o convite." }; const { error: memberError } = await current.supabase.from("clinic_members").upsert({ clinic_id: current.clinicId, user_id: data.user.id, role: parsed.data.role, status: "invited", created_by: current.user.id }, { onConflict: "clinic_id,user_id" }); if (memberError) return { error: "Convite enviado, mas não foi possível vincular o usuário." }; await current.supabase.from("clinic_audit_logs").insert({ clinic_id: current.clinicId, actor_id: current.user.id, target_user_id: data.user.id, event_type: "member_invited", metadata: { role: parsed.data.role } }); revalidatePath("/settings/team"); return { success: "Convite enviado." }; }
export async function updateClinicMember(id: string, input: { role?: ClinicRole; status?: "active" | "inactive" }) { const current = await context(); if ("error" in current) return { error: current.error }; if (input.role === "platform_admin") return { error: "Este papel não pode ser atribuído pela clínica." }; const { data: target } = await current.supabase.from("clinic_members").select("user_id, role").eq("id", id).eq("clinic_id", current.clinicId).maybeSingle(); if (!target) return { error: "Vínculo não encontrado." }; const { error } = await current.supabase.from("clinic_members").update(input).eq("id", id).eq("clinic_id", current.clinicId); if (error) return { error: "Não foi possível atualizar o vínculo." }; await current.supabase.from("clinic_audit_logs").insert({ clinic_id: current.clinicId, actor_id: current.user.id, target_user_id: target.user_id, event_type: "member_updated", metadata: input }); revalidatePath("/settings/team"); return { success: "Usuário atualizado." }; }
