import { ArrowLeft, CalendarClock, Stethoscope, UserRound } from "lucide-react";
import Link from "next/link";
import { notFound } from "next/navigation";

import { getAppointment } from "@/app/(dashboard)/appointments/actions";
import { AppointmentActions } from "@/components/appointments/appointment-actions";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { appointmentStatusLabels, appointmentTypeLabels } from "@/lib/appointments/types";

function Detail({ label, value }: { label: string; value?: string | null }) { return <div><p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">{label}</p><p className="mt-1 whitespace-pre-wrap text-sm">{value || "Não informado"}</p></div>; }
export default async function AppointmentPage({ params }: { params: Promise<{ id: string }> }) { const { id } = await params; const appointment = await getAppointment(id); if (!appointment) notFound(); return <section><Button variant="ghost" size="sm" render={<Link href="/appointments" />} className="mb-3 -ml-2"><ArrowLeft /> Agenda</Button><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h1 className="text-2xl font-semibold tracking-[-0.03em] sm:text-3xl">{appointment.title}</h1><Badge variant={appointment.status === "cancelled" || appointment.status === "no_show" ? "destructive" : "secondary"}>{appointmentStatusLabels[appointment.status]}</Badge></div><p className="mt-2 text-sm text-muted-foreground">{appointmentTypeLabels[appointment.appointment_type]}</p></div></div><div className="mt-5"><AppointmentActions id={id} status={appointment.status} patientId={appointment.patient_id} professionalId={appointment.professional_id} /></div><div className="mt-7 grid gap-6 lg:grid-cols-2"><Card className="shadow-none"><CardHeader><CardTitle className="flex items-center gap-2"><CalendarClock className="size-4 text-primary" /> Data e horário</CardTitle></CardHeader><CardContent className="grid gap-5 sm:grid-cols-2"><Detail label="Data" value={new Intl.DateTimeFormat("pt-BR", { dateStyle: "long" }).format(new Date(`${appointment.appointment_date}T12:00:00`))} /><Detail label="Horário" value={`${appointment.start_time.slice(0, 5)}–${appointment.end_time.slice(0, 5)}`} /></CardContent></Card><Card className="shadow-none"><CardHeader><CardTitle className="flex items-center gap-2"><UserRound className="size-4 text-primary" /> Atendimento</CardTitle></CardHeader><CardContent className="grid gap-5 sm:grid-cols-2"><Detail label="Paciente" value={appointment.patient?.full_name} /><Detail label="Telefone" value={appointment.patient?.phone} /><Detail label="Profissional" value={appointment.professional?.full_name} /><Detail label="Tipo" value={appointmentTypeLabels[appointment.appointment_type]} /></CardContent></Card><Card className="shadow-none lg:col-span-2"><CardHeader><CardTitle className="flex items-center gap-2"><Stethoscope className="size-4 text-primary" /> Informações</CardTitle></CardHeader><CardContent className="grid gap-5 sm:grid-cols-2"><Detail label="Observações" value={appointment.notes} /><Detail label="Motivo do cancelamento" value={appointment.cancellation_reason} />{appointment.cancelled_at && <Detail label="Cancelada em" value={new Date(appointment.cancelled_at).toLocaleString("pt-BR")} />}</CardContent></Card></div></section>; }
