"use client";

import { zodResolver } from "@hookform/resolvers/zod";
import { ArrowLeft, Loader2 } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { useForm } from "react-hook-form";
import { toast } from "sonner";

import { createAppointment, updateAppointment } from "@/app/(dashboard)/appointments/actions";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { appointmentSchema, type AppointmentFormValues } from "@/lib/appointments/schema";
import { appointmentStatusLabels, type Appointment, type Doctor } from "@/lib/appointments/types";

function toInputDate(value?: string) { return value ? new Date(value).toISOString().slice(0, 16) : ""; }
export function AppointmentForm({ appointment, patients, doctors, currentUserId }: { appointment?: Appointment; patients: { id: string; full_name: string }[]; doctors: Doctor[]; currentUserId: string }) {
  const router = useRouter(); const [saving, setSaving] = useState(false);
  const form = useForm<AppointmentFormValues>({ resolver: zodResolver(appointmentSchema), defaultValues: { patient_id: appointment?.patient_id ?? "", doctor_id: appointment?.doctor_id ?? currentUserId, starts_at: toInputDate(appointment?.starts_at), ends_at: toInputDate(appointment?.ends_at), status: appointment?.status ?? "scheduled", appointment_type: appointment?.appointment_type ?? "Consulta", notes: appointment?.notes ?? "", cancellation_reason: appointment?.cancellation_reason ?? "" } });
  async function submit(values: AppointmentFormValues) { setSaving(true); const normalized = { ...values, starts_at: new Date(values.starts_at).toISOString(), ends_at: new Date(values.ends_at).toISOString() }; const result = appointment ? await updateAppointment(appointment.id, normalized) : await createAppointment(normalized); setSaving(false); if (result.error) return toast.error(result.error); toast.success(result.success); router.push("/appointments"); router.refresh(); }
  return <form onSubmit={form.handleSubmit(submit)} className="space-y-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><Button render={<Link href="/appointments" />} variant="ghost" size="sm" className="-ml-2 mb-2"><ArrowLeft /> Agenda</Button><h1 className="text-2xl font-semibold tracking-[-0.03em] sm:text-3xl">{appointment ? "Reagendar consulta" : "Nova consulta"}</h1><p className="mt-1 text-sm text-muted-foreground">Defina paciente, profissional e horário do atendimento.</p></div><Button type="submit" disabled={saving}>{saving && <Loader2 className="animate-spin" />}{appointment ? "Salvar alterações" : "Agendar consulta"}</Button></div><section className="grid gap-5 rounded-xl border bg-card p-5 shadow-none md:grid-cols-2"><div><label className="mb-1.5 block text-sm font-medium">Paciente</label><select className="h-9 w-full rounded-md border bg-background px-3 text-sm" {...form.register("patient_id")}><option value="">Selecione</option>{patients.map((patient) => <option key={patient.id} value={patient.id}>{patient.full_name}</option>)}</select><p className="mt-1 text-xs text-destructive">{form.formState.errors.patient_id?.message}</p></div><div><label className="mb-1.5 block text-sm font-medium">Médico</label><select className="h-9 w-full rounded-md border bg-background px-3 text-sm" {...form.register("doctor_id")}><option value="">Selecione</option>{doctors.map((doctor) => <option key={doctor.id} value={doctor.id}>{doctor.full_name || "Profissional"}</option>)}{!doctors.length && currentUserId && <option value={currentUserId}>Profissional atual</option>}</select><p className="mt-1 text-xs text-destructive">{form.formState.errors.doctor_id?.message}</p></div><div><label className="mb-1.5 block text-sm font-medium">Início</label><Input type="datetime-local" {...form.register("starts_at")} /><p className="mt-1 text-xs text-destructive">{form.formState.errors.starts_at?.message}</p></div><div><label className="mb-1.5 block text-sm font-medium">Término</label><Input type="datetime-local" {...form.register("ends_at")} /><p className="mt-1 text-xs text-destructive">{form.formState.errors.ends_at?.message}</p></div><div><label className="mb-1.5 block text-sm font-medium">Tipo</label><Input {...form.register("appointment_type")} /></div><div><label className="mb-1.5 block text-sm font-medium">Status</label><select className="h-9 w-full rounded-md border bg-background px-3 text-sm" {...form.register("status")}>{Object.entries(appointmentStatusLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div><div className="md:col-span-2"><label className="mb-1.5 block text-sm font-medium">Observações</label><textarea className="min-h-24 w-full rounded-md border bg-background px-3 py-2 text-sm" {...form.register("notes")} /></div></section></form>;
}
