"use server";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { clinicalDocumentTypes, type ClinicalDocument, type ClinicalDocumentType, type PrescriptionItem } from "@/lib/clinical-documents/types";
import { createClient } from "@/lib/supabase/server";
const uuid=z.string().uuid();
function documentDatabaseError(message?: string) {
  const normalized = message ?? "";
  if (normalized.includes("clinical_documents") || normalized.includes("prescription_items") || normalized.includes("PGRST205")) return "O módulo de documentos ainda não foi aplicado ao banco. Execute as migrations 20260711180000 e 20260711190000 no Supabase.";
  return normalized || "Não foi possível concluir a operação no documento.";
}
async function context(){const supabase=await createClient();if(!supabase)return{error:"Supabase não configurado." as const};const{data:auth}=await supabase.auth.getUser();if(!auth.user)return{error:"Sessão expirada." as const};const{data:profile}=await supabase.from("profiles").select("active_clinic_id").eq("id",auth.user.id).maybeSingle();if(!profile?.active_clinic_id)return{error:"Selecione uma clínica ativa." as const};const{data:member}=await supabase.from("clinic_members").select("role").eq("clinic_id",profile.active_clinic_id).eq("user_id",auth.user.id).eq("status","active").maybeSingle();if(!member)return{error:"Sem vínculo ativo com a clínica." as const};return{supabase,userId:auth.user.id,clinicId:profile.active_clinic_id,error:null};}
function refresh(appointmentId:string,id?:string){revalidatePath(`/consultas/${appointmentId}/documentos`);revalidatePath(`/consultas/${appointmentId}/prontuario`);if(id){revalidatePath(`/documentos/${id}`);revalidatePath(`/documentos/${id}/imprimir`);}}
export async function listAppointmentDocuments(appointmentId:string){if(!uuid.safeParse(appointmentId).success)return{documents:[] as ClinicalDocument[],error:"Consulta inválida."};const c=await context();if(c.error)return{documents:[] as ClinicalDocument[],error:c.error};const{data,error}=await c.supabase.from("clinical_documents").select("*").eq("clinic_id",c.clinicId).eq("appointment_id",appointmentId).is("deleted_at",null).order("created_at",{ascending:false});return{documents:(data??[]) as ClinicalDocument[],error:error?"Não foi possível carregar os documentos.":null};}
export async function createClinicalDocument(appointmentId:string,type:ClinicalDocumentType){if(!uuid.safeParse(appointmentId).success||!clinicalDocumentTypes.includes(type))return{error:"Dados inválidos."};const c=await context();if(c.error)return{error:c.error};const{data:appointment}=await c.supabase.from("appointments").select("id,patient_id,professional_id").eq("id",appointmentId).eq("clinic_id",c.clinicId).maybeSingle();if(!appointment)return{error:"Consulta não encontrada."};if(appointment.professional_id!==c.userId)return{error:"Somente o profissional responsável pode criar documentos."};const{data:record}=await c.supabase.from("medical_records").select("id").eq("appointment_id",appointmentId).is("deleted_at",null).maybeSingle();const title=clinicalDocumentTypes.includes(type)?({prescription:"Receita simples",special_prescription:"Receita de controle especial",medical_certificate:"Atestado médico",attendance_declaration:"Declaração de comparecimento",exam_request:"Solicitação de exames",referral:"Encaminhamento",patient_guidance:"Orientações ao paciente"} as Record<string,string>)[type]:"Documento";const{data,error}=await c.supabase.from("clinical_documents").insert({appointment_id:appointmentId,medical_record_id:record?.id??null,document_type:type,title,content:{text:""}}).select("id").single();if(error||!data)return{error:documentDatabaseError(error?.message)};refresh(appointmentId,data.id);return{id:data.id};}
export async function getClinicalDocument(id:string){if(!uuid.safeParse(id).success)return null;const c=await context();if(c.error)return null;const{data}=await c.supabase.from("clinical_documents").select("*, patient:patients(full_name,social_name,cpf,birth_date)").eq("id",id).eq("clinic_id",c.clinicId).is("deleted_at",null).maybeSingle();if(!data)return null;const[{data:profile},{data:professionalProfile},{data:clinic},{data:items}]=await Promise.all([c.supabase.from("profiles").select("full_name").eq("id",data.professional_id).maybeSingle(),c.supabase.from("professional_profiles").select("professional_name,profession,council,council_number,council_state,specialty,rqe,signature_url").eq("clinic_id",c.clinicId).eq("user_id",data.professional_id).maybeSingle(),c.supabase.from("clinics").select("name,legal_name,cnpj,email,phone,whatsapp,address,address_number,address_complement,neighborhood,city,state,zip_code,logo_url").eq("id",c.clinicId).maybeSingle(),c.supabase.from("prescription_items").select("*").eq("document_id",id).order("sort_order")]);return{...data,patient:Array.isArray(data.patient)?data.patient[0]:data.patient,professional:{full_name:profile?.full_name??null,...professionalProfile},clinic,items:items??[]} as ClinicalDocument;}
export async function saveClinicalDocument(id:string,title:string,content:Record<string,string|boolean>,items:PrescriptionItem[]){if(!uuid.safeParse(id).success)return{error:"Documento inválido."};const c=await context();if(c.error)return{error:c.error};const{data:doc}=await c.supabase.from("clinical_documents").select("id,appointment_id,status,professional_id").eq("id",id).eq("clinic_id",c.clinicId).maybeSingle();if(!doc)return{error:"Documento não encontrado."};if(doc.status!=="draft")return{error:"Documento emitido não pode ser alterado."};if(doc.professional_id!==c.userId)return{error:"Sem permissão para editar."};const{error}=await c.supabase.from("clinical_documents").update({title:title.trim(),content}).eq("id",id);if(error)return{error:error.message};const del=await c.supabase.from("prescription_items").delete().eq("document_id",id);if(del.error)return{error:"Não foi possível atualizar os itens."};if(items.length){const inserted=await c.supabase.from("prescription_items").insert(items.map((item,index)=>({...item,id:undefined,clinic_id:c.clinicId,document_id:id,sort_order:index})));if(inserted.error)return{error:"Não foi possível salvar os medicamentos."};}refresh(doc.appointment_id,id);return{success:"Rascunho salvo."};}
export async function issueClinicalDocument(id:string){const c=await context();if(c.error)return{error:c.error};const{data:doc}=await c.supabase.from("clinical_documents").select("appointment_id").eq("id",id).eq("clinic_id",c.clinicId).maybeSingle();if(!doc)return{error:"Documento não encontrado."};const{error}=await c.supabase.rpc("issue_clinical_document",{target_document_id:id});if(error)return{error:error.message};refresh(doc.appointment_id,id);return{success:"Documento emitido."};}
export async function cancelClinicalDocument(id:string,reason:string){const c=await context();if(c.error)return{error:c.error};const{data:doc}=await c.supabase.from("clinical_documents").select("appointment_id").eq("id",id).eq("clinic_id",c.clinicId).maybeSingle();if(!doc)return{error:"Documento não encontrado."};const{error}=await c.supabase.rpc("cancel_clinical_document",{target_document_id:id,reason});if(error)return{error:error.message};refresh(doc.appointment_id,id);return{success:"Documento cancelado sem apagar o histórico."};}
export async function markDocumentPrinted(id:string){const c=await context();if(c.error)return;await c.supabase.rpc("mark_clinical_document_printed",{target_document_id:id});}
export async function savePrescriptionFavorite(documentId:string,name:string){if(!uuid.safeParse(documentId).success||!name.trim())return{error:"Informe um nome para o modelo."};const c=await context();if(c.error)return{error:c.error};const doc=await getClinicalDocument(documentId);if(!doc||!(["prescription","special_prescription"] as string[]).includes(doc.document_type))return{error:"Receita não encontrada."};const{error}=await c.supabase.from("favorite_prescriptions").upsert({clinic_id:c.clinicId,professional_id:c.userId,name:name.trim(),document_type:doc.document_type,content:doc.content,items:doc.items??[]},{onConflict:"clinic_id,professional_id,name"});return error?{error:error.message}:{success:"Modelo favorito salvo."};}
