"use server";

import { revalidatePath } from "next/cache";
import { z } from "zod";
import { createClient } from "@/lib/supabase/server";

const optionalUrl=z.string().trim().url().or(z.literal("")).optional();
const clinicSchema=z.object({name:z.string().trim().min(2),legal_name:z.string().trim().optional(),cnpj:z.string().trim().optional(),cnes:z.string().trim().optional(),logo_url:optionalUrl,phone:z.string().trim().optional(),whatsapp:z.string().trim().optional(),email:z.string().trim().email().or(z.literal("")).optional(),website:optionalUrl,instagram:z.string().trim().optional(),favicon_url:optionalUrl,zip_code:z.string().trim().optional(),address:z.string().trim().optional(),address_number:z.string().trim().optional(),address_complement:z.string().trim().optional(),neighborhood:z.string().trim().optional(),city:z.string().trim().optional(),state:z.string().trim().max(2).optional()});
const professionalSchema=z.object({user_id:z.string().uuid(),professional_name:z.string().trim().optional(),profession:z.string().trim().optional(),council:z.string().trim().optional(),council_number:z.string().trim().optional(),council_state:z.string().trim().max(2).optional(),specialty:z.string().trim().optional(),sub_specialty:z.string().trim().optional(),rqe:z.string().trim().optional(),phone:z.string().trim().optional(),email:z.string().trim().email().or(z.literal("")).optional(),photo_url:optionalUrl,signature_url:optionalUrl,stamp_url:optionalUrl,is_active:z.boolean(),is_responsible:z.boolean()});
const settingsSchema=z.record(z.string(),z.unknown());
async function context(admin=false){const supabase=await createClient();if(!supabase)return{error:"Supabase não configurado." as const};const{data:{user}}=await supabase.auth.getUser();if(!user)return{error:"Sessão expirada." as const};const{data:profile}=await supabase.from("profiles").select("active_clinic_id").eq("id",user.id).maybeSingle();if(!profile?.active_clinic_id)return{error:"Selecione uma clínica ativa." as const};const{data:member}=await supabase.from("clinic_members").select("role,status").eq("clinic_id",profile.active_clinic_id).eq("user_id",user.id).maybeSingle();if(!member||member.status!=="active")return{error:"Sem vínculo ativo com a clínica." as const};if(admin&&member.role!=="clinic_admin")return{error:"Somente administradores podem alterar esta configuração." as const};return{supabase,clinicId:profile.active_clinic_id,userId:user.id,role:member.role,error:null};}
const nil=(value?:string)=>value?.trim()||null;
export async function getClinicSettings(){const c=await context(false);if(c.error)return{clinic:null,professionals:[],settings:{clinic:null,document:null,schedule:null,ai:null},error:c.error};const[{data:clinic},{data:members},{data:clinicSettings},{data:documentSettings},{data:scheduleSettings},{data:aiSettings}]=await Promise.all([c.supabase.from("clinics").select("*").eq("id",c.clinicId).maybeSingle(),c.supabase.from("clinic_members").select("user_id,role,status").eq("clinic_id",c.clinicId).eq("status","active"),c.supabase.from("clinic_settings").select("*").eq("clinic_id",c.clinicId).maybeSingle(),c.supabase.from("document_settings").select("*").eq("clinic_id",c.clinicId).maybeSingle(),c.supabase.from("schedule_settings").select("*").eq("clinic_id",c.clinicId).maybeSingle(),c.supabase.from("ai_settings").select("*").eq("clinic_id",c.clinicId).maybeSingle()]);const ids=(members??[]).map(m=>m.user_id);const[{data:profiles},{data:professionalProfiles}]=await Promise.all([ids.length?c.supabase.from("profiles").select("id,full_name,email,phone").in("id",ids):Promise.resolve({data:[]}),ids.length?c.supabase.from("professional_profiles").select("*").eq("clinic_id",c.clinicId).in("user_id",ids):Promise.resolve({data:[]})]);return{clinic,professionals:(members??[]).map(member=>({...member,profile:(profiles??[]).find(p=>p.id===member.user_id)??null,professional:(professionalProfiles??[]).find(p=>p.user_id===member.user_id)??null})),settings:{clinic:clinicSettings,document:documentSettings,schedule:scheduleSettings,ai:aiSettings},error:null};}
export async function saveClinicSettings(input:unknown){const parsed=clinicSchema.safeParse(input);if(!parsed.success)return{error:parsed.error.issues[0]?.message??"Dados inválidos."};const c=await context(true);if(c.error)return{error:c.error};const value=parsed.data;const{error}=await c.supabase.from("clinics").update({...value,legal_name:nil(value.legal_name),cnpj:nil(value.cnpj),cnes:nil(value.cnes),logo_url:nil(value.logo_url),phone:nil(value.phone),whatsapp:nil(value.whatsapp),email:nil(value.email),website:nil(value.website),instagram:nil(value.instagram),favicon_url:nil(value.favicon_url),zip_code:nil(value.zip_code),address:nil(value.address),address_number:nil(value.address_number),address_complement:nil(value.address_complement),neighborhood:nil(value.neighborhood),city:nil(value.city),state:nil(value.state)?.toUpperCase()??null}).eq("id",c.clinicId);if(error)return{error:error.message};revalidatePath("/configuracoes/clinica");return{success:"Dados da clínica salvos."};}
export async function saveProfessionalProfile(input:unknown){const parsed=professionalSchema.safeParse(input);if(!parsed.success)return{error:parsed.error.issues[0]?.message??"Dados inválidos."};const c=await context(false);if(c.error)return{error:c.error};if(parsed.data.user_id!==c.userId&&c.role!=="clinic_admin")return{error:"Somente administradores podem editar outro profissional."};const v=parsed.data;const{error}=await c.supabase.from("professional_profiles").upsert({clinic_id:c.clinicId,...v,updated_by:c.userId,professional_name:nil(v.professional_name),profession:nil(v.profession),council:nil(v.council),council_number:nil(v.council_number),council_state:nil(v.council_state)?.toUpperCase()??null,specialty:nil(v.specialty),sub_specialty:nil(v.sub_specialty),rqe:nil(v.rqe),phone:nil(v.phone),email:nil(v.email),photo_url:nil(v.photo_url),signature_url:nil(v.signature_url),stamp_url:nil(v.stamp_url)},{onConflict:"clinic_id,user_id"});if(error)return{error:error.message};revalidatePath("/configuracoes/profissionais");return{success:"Perfil profissional salvo."};}
export async function saveSettings(kind:"clinic_settings"|"document_settings"|"schedule_settings"|"ai_settings",input:unknown){const c=await context(true);if(c.error)return{error:c.error};const parsed=settingsSchema.safeParse(input);if(!parsed.success)return{error:"Dados inválidos."};const{error}=await c.supabase.from(kind).upsert({clinic_id:c.clinicId,...(input as Record<string,unknown>),updated_by:c.userId},{onConflict:"clinic_id"});if(error)return{error:"Não foi possível salvar esta configuração."};revalidatePath("/configuracoes");revalidatePath(`/configuracoes/${kind.replace("_settings","")}`);return{success:"Configuração salva com sucesso."};}
export async function createClinicAssetUpload(filename:string,contentType:string){const c=await context(true);if(c.error)return{error:c.error};if(!["image/png","image/jpeg","image/svg+xml"].includes(contentType))return{error:"Formato de logomarca não suportado."};const safe=filename.toLowerCase().replace(/[^a-z0-9._-]+/g,"-");const path=`${c.clinicId}/${crypto.randomUUID()}-${safe}`;const{data,error}=await c.supabase.storage.from("clinic-assets").createSignedUploadUrl(path);if(error||!data)return{error:"Não foi possível preparar o upload da logomarca."};return{path,token:data.token,publicUrl:c.supabase.storage.from("clinic-assets").getPublicUrl(path).data.publicUrl};}
export async function removeClinicAsset(path:string){const c=await context(true);if(c.error)return{error:c.error};const normalized=path.includes("/clinic-assets/")?path.split("/clinic-assets/")[1]:path;if(!normalized.startsWith(`${c.clinicId}/`))return{error:"Arquivo inválido."};const{error}=await c.supabase.storage.from("clinic-assets").remove([normalized]);return error?{error:"Não foi possível remover a logomarca."}:{success:"Logomarca removida."};}
