"use server";

import { revalidatePath } from "next/cache";
import { z } from "zod";
import { createClient } from "@/lib/supabase/server";

const clinicSchema=z.object({name:z.string().trim().min(2),legal_name:z.string().trim().optional(),cnpj:z.string().trim().optional(),cnes:z.string().trim().optional(),logo_url:z.string().trim().url().or(z.literal("")).optional(),phone:z.string().trim().optional(),whatsapp:z.string().trim().optional(),email:z.string().trim().email().or(z.literal("")).optional(),zip_code:z.string().trim().optional(),address:z.string().trim().optional(),address_number:z.string().trim().optional(),address_complement:z.string().trim().optional(),neighborhood:z.string().trim().optional(),city:z.string().trim().optional(),state:z.string().trim().max(2).optional()});
const professionalSchema=z.object({user_id:z.string().uuid(),professional_name:z.string().trim().optional(),profession:z.string().trim().optional(),council:z.string().trim().optional(),council_number:z.string().trim().optional(),council_state:z.string().trim().max(2).optional(),specialty:z.string().trim().optional(),rqe:z.string().trim().optional(),phone:z.string().trim().optional(),email:z.string().trim().email().or(z.literal("")).optional(),signature_url:z.string().trim().url().or(z.literal("")).optional(),is_active:z.boolean()});
async function context(admin=false){const supabase=await createClient();if(!supabase)return{error:"Supabase não configurado." as const};const{data:{user}}=await supabase.auth.getUser();if(!user)return{error:"Sessão expirada." as const};const{data:profile}=await supabase.from("profiles").select("active_clinic_id").eq("id",user.id).maybeSingle();if(!profile?.active_clinic_id)return{error:"Selecione uma clínica ativa." as const};const{data:member}=await supabase.from("clinic_members").select("role,status").eq("clinic_id",profile.active_clinic_id).eq("user_id",user.id).maybeSingle();if(!member||member.status!=="active")return{error:"Sem vínculo ativo com a clínica." as const};if(admin&&member.role!=="clinic_admin")return{error:"Somente administradores podem alterar esta configuração." as const};return{supabase,clinicId:profile.active_clinic_id,userId:user.id,role:member.role,error:null};}
const nil=(value?:string)=>value?.trim()||null;
export async function getClinicSettings(){const c=await context(true);if(c.error)return{clinic:null,professionals:[],error:c.error};const[{data:clinic},{data:members}]=await Promise.all([c.supabase.from("clinics").select("*").eq("id",c.clinicId).maybeSingle(),c.supabase.from("clinic_members").select("user_id,role,status").eq("clinic_id",c.clinicId).in("role",["doctor","clinic_admin"]).eq("status","active")]);const ids=(members??[]).map(m=>m.user_id);const[{data:profiles},{data:professionalProfiles}]=await Promise.all([ids.length?c.supabase.from("profiles").select("id,full_name,email,phone").in("id",ids):Promise.resolve({data:[]}),ids.length?c.supabase.from("professional_profiles").select("*").eq("clinic_id",c.clinicId).in("user_id",ids):Promise.resolve({data:[]})]);return{clinic,professionals:(members??[]).map(member=>({...member,profile:(profiles??[]).find(p=>p.id===member.user_id)??null,professional:(professionalProfiles??[]).find(p=>p.user_id===member.user_id)??null})),error:null};}
export async function saveClinicSettings(input:unknown){const parsed=clinicSchema.safeParse(input);if(!parsed.success)return{error:parsed.error.issues[0]?.message??"Dados inválidos."};const c=await context(true);if(c.error)return{error:c.error};const value=parsed.data;const{error}=await c.supabase.from("clinics").update({...value,legal_name:nil(value.legal_name),cnpj:nil(value.cnpj),cnes:nil(value.cnes),logo_url:nil(value.logo_url),phone:nil(value.phone),whatsapp:nil(value.whatsapp),email:nil(value.email),zip_code:nil(value.zip_code),address:nil(value.address),address_number:nil(value.address_number),address_complement:nil(value.address_complement),neighborhood:nil(value.neighborhood),city:nil(value.city),state:nil(value.state)?.toUpperCase()??null}).eq("id",c.clinicId);if(error)return{error:error.message};revalidatePath("/configuracoes/clinica");return{success:"Dados da clínica salvos."};}
export async function saveProfessionalProfile(input:unknown){const parsed=professionalSchema.safeParse(input);if(!parsed.success)return{error:parsed.error.issues[0]?.message??"Dados inválidos."};const c=await context(true);if(c.error)return{error:c.error};const v=parsed.data;const{error}=await c.supabase.from("professional_profiles").upsert({clinic_id:c.clinicId,...v,professional_name:nil(v.professional_name),profession:nil(v.profession),council:nil(v.council),council_number:nil(v.council_number),council_state:nil(v.council_state)?.toUpperCase()??null,specialty:nil(v.specialty),rqe:nil(v.rqe),phone:nil(v.phone),email:nil(v.email),signature_url:nil(v.signature_url)},{onConflict:"clinic_id,user_id"});if(error)return{error:error.message};revalidatePath("/configuracoes/profissionais");return{success:"Perfil profissional salvo."};}
